package com.dboycht.keyforge.keyboard

import com.dboycht.keyforge.layout.KeySpec

/**
 * How a key behaves when the finger stays down after the first keystroke.
 *
 * This is the distinction that a physical keyboard makes, and that this app originally got wrong:
 *
 * - [ONESHOT] - one keystroke per touch. Used by keys where repeating is meaningless or harmful.
 * - [HOLD] - the key goes **down and stays down** until the finger lifts. This is what a real
 *   keyboard does: holding `a` does not alternate press/release, it reports "a is still held" and
 *   lets the *host* decide whether to repeat the character (Windows typematic repeat). Games
 *   depend on this - a held key is "keep moving", so any release is read as "stop".
 * - [PULSE] - alternating down/up while held, i.e. the host sees repeated, separate keystrokes.
 *   This is what the app used to do for every key, and it is wrong for games: the character walks
 *   in stutters because every pulse is a release. It is kept only as an explicit opt-in for a
 *   host that somehow ignores a held key.
 *
 * Default is [HOLD] because that is what "like a computer keyboard" means.
 */
internal enum class RepeatMode {
    ONESHOT,
    HOLD,
    PULSE,
}

/**
 * The key-repeat schedule for a held key.
 *
 * A physical keyboard's own repeat (typematic) is generated by the **host**, not the keyboard: the
 * keyboard just keeps reporting the same held key. So under [RepeatMode.HOLD] this app must not
 * produce characters itself; it only has two jobs:
 *
 * 1. **hold** the key down from the first press until the finger lifts, and
 * 2. **re-send the same report** every [keepAliveMs] so a report lost in a crowded link self-heals
 *    and the host never concludes the key was released. This is a keep-alive, not a keystroke - the
 *    report content does not change.
 *
 * [delayMs]/[intervalMs] are the fallback typematic timing used by [RepeatMode.PULSE] (and by hosts
 * that do not do their own repeat).
 */
internal data class RepeatSchedule(
    val mode: RepeatMode,
    val delayMs: Long,
    val intervalMs: Long,
    val keepAliveMs: Long = DEFAULT_KEEP_ALIVE_MS,
) {
    companion object {
        /** Re-sending an unchanged report this often is enough to survive a dropped report. */
        const val DEFAULT_KEEP_ALIVE_MS = 50L

        /** One keystroke per touch. */
        val ONESHOT = RepeatSchedule(RepeatMode.ONESHOT, 0L, 0L)

        /**
         * The physical-keyboard behaviour: hold, with a keep-alive.
         *
         * [delayMs]/[intervalMs] are ignored in this mode (the host owns the repeat rate), but they
         * are carried so a UI can display the effective typing rate.
         */
        fun hold(
            delayMs: Long = KeySpec.AUTO_REPEAT_DELAY_MS,
            intervalMs: Long = KeySpec.AUTO_REPEAT_INTERVAL_MS,
            keepAliveMs: Long = DEFAULT_KEEP_ALIVE_MS,
        ) = RepeatSchedule(RepeatMode.HOLD, delayMs, intervalMs, keepAliveMs)

        /** Alternating down/up - the legacy behaviour, opt-in only. */
        fun pulse(
            delayMs: Long = KeySpec.AUTO_REPEAT_DELAY_MS,
            intervalMs: Long = KeySpec.AUTO_REPEAT_INTERVAL_MS,
        ) = RepeatSchedule(RepeatMode.PULSE, delayMs, intervalMs)
    }
}

/**
 * Decides what a held key should do over time, as a state machine driven by callbacks.
 *
 * Extracted from the Compose gesture handling on purpose: the behaviour that broke the user's game
 * (pressing and releasing instead of holding) is pure schedule logic, so it is unit tested here
 * rather than only being observable by watching a game character stutter.
 *
 * [AutoRepeater] is deliberately passive - the caller owns the coroutine and the real delay, and
 * passes elapsed time in. That keeps every branch testable without a running dispatcher.
 */
internal class AutoRepeater(
    private val schedule: RepeatSchedule,
    /**
     * Send the "key is down" report. Called once at press, and once per keep-alive/pulse.
     *
     * [isRepeat] is true for every call after the first, which lets the caller send a byte-identical
     * keep-alive **without** logging it as a new keystroke (a 50ms cadence would otherwise flood the
     * event log, which this project has been bitten by before).
     */
    private val onDown: (isRepeat: Boolean) -> Unit,
    /** Send the "key is up" report. Must be called exactly once per press, at the end. */
    private val onUp: () -> Unit,
) {
    private var held = false
    private var elapsedMs = 0L
    private var nextRepeatAtMs = 0L

    /** True between [press] and [release]. */
    val isHeld: Boolean get() = held

    /**
     * The finger went down.
     *
     * Sends the first keystroke immediately (so a normal tap is never swallowed by the repeat
     * delay) and then arms the schedule.
     *
     * Under [RepeatMode.HOLD] the first keep-alive is due after [RepeatSchedule.keepAliveMs], **not**
     * after the typing delay: a keep-alive repeats an unchanged report, so there is no reason to wait
     * for a "repeat delay" - and waiting would leave a real gap where a single dropped report would
     * read as a release.
     */
    fun press() {
        held = true
        elapsedMs = 0L
        nextRepeatAtMs = when (schedule.mode) {
            RepeatMode.PULSE -> schedule.delayMs
            RepeatMode.HOLD, RepeatMode.ONESHOT -> schedule.keepAliveMs
        }
        onDown(false)
    }

    /**
     * [deltaMs] have passed with the finger still down.
     *
     * **One report pair per tick at most, and a tick that lands late is skipped rather than
     * caught up.** A burst of catch-up keystrokes is never what the user did, so trading a little
     * cadence accuracy for "never emit a burst" is the right way round: the caller ticks far more
     * often than the cadence (25ms against a 50ms keep-alive), so a late tick costs one keep-alive
     * and the next tick delivers one anyway. If the caller stalls long enough for the link to go
     * quiet, [press] is the way back - a fresh press re-arms the schedule.
     *
     * Returns true if this call sent something, which lets the caller decide how to pace itself
     * (and lets tests assert the exact schedule).
     */
    fun advance(deltaMs: Long): Boolean {
        if (!held || schedule.mode == RepeatMode.ONESHOT) return false
        elapsedMs += deltaMs
        if (elapsedMs < nextRepeatAtMs) return false

        when (schedule.mode) {
            // The key never left the down state: re-sending the identical report is a keep-alive,
            // not a new keystroke. This is the whole fix for "pulsing" input in games.
            RepeatMode.HOLD -> {
                onDown(true)
                nextRepeatAtMs += schedule.keepAliveMs
            }
            // Opt-in legacy behaviour: a complete down/up pair per due tick.
            RepeatMode.PULSE -> {
                onUp()
                onDown(true)
                nextRepeatAtMs += schedule.intervalMs
            }
            RepeatMode.ONESHOT -> Unit
        }
        return true
    }

    /**
     * The finger lifted: the key must be released **exactly once**, whatever mode was in force.
     *
     * Returns true if an up report was sent. Calling this without a press, or twice, sends nothing -
     * a stray extra release would silently clear a key another finger is still holding.
     */
    fun release(): Boolean {
        if (!held) return false
        held = false
        onUp()
        return true
    }
}
